---
- name: Ensure env file exists
  become: true
  ansible.builtin.file:
    path: /etc/{{ service_name }}.env
    state: touch
    mode: "0644"
    modification_time: preserve
    access_time: preserve
  tags: [not-deploy]

- name: Copy unit file: {{ service_name }}
  become: true
  ansible.builtin.template:
    src: "unit-files/docker.service"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: "0644"
  notify: Reload systemd daemon
  tags: [not-deploy]

- name: "Env file"
  become: true
  ansible.builtin.copy:
    src: "{{ env_file }}"
    dest: /etc/{{ service_name }}.env
    mode: "0644"

- name: "Pull the image: {{ service_name }}"
  become: true
  community.docker.docker_image_pull:
    name:
      "734485531948.dkr.ecr.us-east-1.amazonaws.com/{{ service_name }}:{{
      tag_name }}"
    pull: always

- name: "Start the container {{ service_name }}"
  become: true
  ansible.builtin.systemd:
    name: "{{ service_name }}.service"
    state: started
    enabled: true
  tags: [not-deploy]

- name: Restart service
  become: true
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
    enabled: true
  tags: [not-provision]
