- name: Betterbike Service
  ansible.builtin.include_role:
    name: bin-service
    apply:
      tags: [betterbike]
  vars:
    service_name: "betterbike"
    env_file: "env/betterbike.env"
    description: "Betterbike Web Service"
    args:
  tags: [betterbike]
