- name: keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG apt Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Ensure correct permissions on GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Import Docker GPG Key
  ansible.builtin.apt_key:
    keyring: /etc/apt/keyrings/docker.asc
    file: /etc/apt/keyrings/docker.asc
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
    state: present
    filename: 'docker'

- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

